#LOGGING
logging:
   config: classpath:config/log4j2.xml
   level:
       root: info
       org.springframework.security: info
       org.hibernate: ERROR

#server
server:
  servlet:
    context-path: /ecms
  address: 0.0.0.0
  port: 8080

#spring
spring:
  application:
    name: ecms-web
  profiles:
    active: dev
  cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848
  servlet:
    multipart:
      maxFileSize: -1
  banner:
    charset: utf-8
    location: classpath:/config/banner.txt
  messages:
    basename: i18n/messages
    encoding: UTF-8
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML5
    cache: false
  jpa:
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    hibernate:
      ddl-auto: update
  quartz:
      #相关属性配置
      properties:
        org:
          quartz:
            scheduler:
              instanceName: clusteredScheduler
              instanceId: AUTO
            jobStore:
              class: org.quartz.impl.jdbcjobstore.JobStoreTX
              driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
              tablePrefix: QRTZ_
              isClustered: true
              clusterCheckinInterval: 10000
              useProperties: false
            threadPool:
              class: org.quartz.simpl.SimpleThreadPool
              threadCount: 10
              threadPriority: 5
              threadsInheritContextClassLoaderOfInitializingThread: true
      #数据库方式
      job-store-type: jdbc
      #初始化表结构,该配置目前版本没有生效
      jdbc:
        initialize-schema: never
debug: false
trace: false
login:
  type: json

--- #dev ---------------------------------------------------------------------------------------------------------
#spring
spring:
  profiles: dev
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/ecms?useUnicode=true&characterEncoding=UTF-8&useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 30
    slave:
      jdbc-url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 20
      max-lifetime: 30000
      idle-timeout: 30000
      data-source-properties:
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          cachePrepStmts: true
          useServerPrepStmts: true
---  #test ---------------------------------------------------------------------------------------------------------
#spring
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/ecms?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30

---  #prod ---------------------------------------------------------------------------------------------------------
#spring
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://rm-bp1dio47i3z5w9z14go.mysql.rds.aliyuncs.com:3306/ecms?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: ecms
    password: ecms
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30









