#LOGGING
logging:
   config: classpath:config/log4j2.xml
   level:
       root: INFO
       org.springframework.web: ERROR
       org.hibernate: ERROR
#spring
spring:
  profiles:
    active: dev
  banner:
    charset: utf-8
    location: classpath:/config/banner.txt
  messages:
    basename: i18n/messages
    encoding: UTF-8
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML5
    cache: false
  jpa:
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    hibernate:
      ddl-auto: update
  # SECURITY OAUTH2 CLIENT (OAuth2ClientProperties)
  security:
   oauth2:
    client:
      registration:
        github-client-1:
          client-id: 89630a412fa314777dc2
          client-secret: c7a29ec26ec7805e78b496ea67cc13e5a9b8bcf0
          client-name: Github User
          provider: github
          scope: user
          access-token-uri: https://github.com/login/oauth/access_token
          user-authorization-uri: https://github.com/login/oauth/authorize
          client-authentication-scheme: form
          registered-redirect-uri: ${site.baseUrl}/github_login
          use-current-uri: false
          authorization-grant-type: authorization_code
          resource:
            user-info-uri: https://api.github.com/user
            prefer-token-info: false
            # SECURITY OAUTH2 SSO (OAuth2SsoProperties)           sso:
            login-path: /github_login
      provider:
        my-oauth-provider:
          authorization-uri: http://localhost:8080/oauth/authorize
          token-uri: http://localhost:8080/oauth/token

debug: false
trace: false
login:
  type: json
#server
server:
  servlet:
    context-path: /ecms
  address: localhost
  port: 8080
--- #dev ---------------------------------------------------------------------------------------------------------
#spring
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/ecms?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30

server:
  servlet:
    context-path: /ecms
  address: localhost
  port: 8080
---  #test ---------------------------------------------------------------------------------------------------------
#spring
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/ecms?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30
server:
  servlet:
    context-path: /ecms
  address: localhost
  port: 8080
---  #prod ---------------------------------------------------------------------------------------------------------
#spring
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://rm-bp1dio47i3z5w9z14go.mysql.rds.aliyuncs.com:3306/ecms?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: ecms
    password: ecms
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30
server:
  servlet:
    context-path: /ecms
  address: localhost
  port: 80








