#LOGGING
logging:
   config: classpath:config/log4j2.xml
   level:
       root: INFO
       org.springframework.web: ERROR
       org.hibernate: ERROR
#spring
spring:
  profiles:
    active: dev
  banner:
    charset: utf-8
    location: classpath:/config/banner.txt
  messages:
    basename: i18n/messages
    encoding: UTF-8
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML5
    cache: false
  jpa:
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    hibernate:
      ddl-auto: update
  # SECURITY OAUTH2 CLIENT (OAuth2ClientProperties  CommonOAuth2Provider)
  security:
   oauth2:
    client:
      registration:
        facebook:
          client-id: 233668646673605
          client-secret: 33b17e044ee6a4fa383f46ec6e28ea1d
        github:
          client-id: bd1c0a783ccdd1c9b9e4
          client-secret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
      provider:
        ecms-oauth-provider:
          authorization-uri: http://localhost:8080/oauth/authorize
          token-uri: http://localhost:8080/oauth/token
          user-info-uri: http://my-auth-server/userinfo
          user-info-authentication-method: header
  quartz:
      #相关属性配置
      properties:
        org:
          quartz:
            scheduler:
              instanceName: clusteredScheduler
              instanceId: AUTO
            jobStore:
              class: org.quartz.impl.jdbcjobstore.JobStoreTX
              driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
              tablePrefix: QRTZ_
              isClustered: true
              clusterCheckinInterval: 10000
              useProperties: false
            threadPool:
              class: org.quartz.simpl.SimpleThreadPool
              threadCount: 10
              threadPriority: 5
              threadsInheritContextClassLoaderOfInitializingThread: true
      #数据库方式
      job-store-type: jdbc
      #初始化表结构,该配置目前版本没有生效
      jdbc:
        initialize-schema: never
debug: false
trace: false

login:
  type: json
#server
server:
  servlet:
    context-path: /ecms
  address: localhost
  port: 8080



--- #dev ---------------------------------------------------------------------------------------------------------
#spring
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/ecms?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30

server:
  servlet:
    context-path: /ecms
  address: localhost
  port: 8080
---  #test ---------------------------------------------------------------------------------------------------------
#spring
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/ecms?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30
server:
  servlet:
    context-path: /ecms
  address: localhost
  port: 8080
---  #prod ---------------------------------------------------------------------------------------------------------
#spring
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://rm-bp1dio47i3z5w9z14go.mysql.rds.aliyuncs.com:3306/ecms?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: ecms
    password: ecms
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30
server:
  servlet:
    context-path: /ecms
  address: localhost
  port: 80








