#LOGGING
logging:
   config: classpath:config/log4j2.xml
   level:
       root: INFO
       org.springframework.web: ERROR
       org.hibernate: ERROR
#spring
spring:
  profiles:
    active: dev
  banner:
    charset: utf-8
    location: classpath:/config/banner.txt
  messages:
    basename: i18n/messages
    encoding: UTF-8
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    hibernate:
      ddl-auto: update

debug: false
trace: false
#server
server:
  servlet:
    context-path: /ecms
  address: localhost
  port: 8080
--- #dev ---------------------------------------------------------------------------------------------------------
#spring
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/ecms?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30

server:
  servlet:
    context-path: /ecms
  address: localhost
  port: 8080
---  #test ---------------------------------------------------------------------------------------------------------
#spring
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/ecms?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30
server:
  servlet:
    context-path: /ecms
  address: localhost
  port: 8080
---  #prod ---------------------------------------------------------------------------------------------------------
#spring
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://rm-bp1dio47i3z5w9z14go.mysql.rds.aliyuncs.com:3306/ecms?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: ecms
    password: ecms
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30
server:
  servlet:
    context-path: /ecms
  address: localhost
  port: 80








